### ISSUE TITLE
How to enrich with local data?

### ISSUE THREAD

**Issue by fr3fou** [GetStream/stream-go2#105]
The example provided uses the built in `Collections` and `Users` API. How do I enrich with data that I store locally in my own database?

**Comment by ferhatelmas** [comment]
We support django/rails/laravel for this purpose because they have a standard ORM mostly but this isn't the case for go. That's why you're alone. 

You can set ids from your DB and read from stream without enrichment, then on the backend, collect ids from the response and replace them and finally send to the client.

If you can come up with a standard solution, we can take over and improve it but in the short term, we don't have any plans to add ORM support such as gorm, go-pg, etc.

**Comment by fr3fou** [comment]
Am I supposed to manually do `id := strings.Split("User:1", ":")[1]` or is there some built in way?

**Comment by ferhatelmas** [comment]
If you're not using our references then it depends on how you save your ids. You can definitely put your own ids as whole like `activity.Actor = myID.String()` then you don't need to any processing since it's just your id.

**Comment by ferhatelmas** [comment]
That being said, I would suggest using similar scheme for your own db tables/entities so that you can know it's a reference and if so, its kind. It would simplify finding them from the response.
