### ISSUE TITLE
Add delete feed support (needs API update)

### ISSUE THREAD

**Issue by Emixam23** [GetStream/stream-go2#93]
Hey!

Maybe it's my mistake but from neither `*client` nor `*FlatFeed` I can find a way to remove a feed, is it possible at least?  Thing is, instead of unfollowing all the related feed, if I could just remove it, it would make it easier to me...

Thanks!

**Comment by ferhatelmas** [comment]
What is the goal here?

1. to unfollow many feeds in one go
2. to delete all activities in a feed in one go

If 1., delete is a wrong keyword and we already have unfollow many support which is only for enterprise (rate limited as 0 otherwise).

If 2., not supported in server. SDK can help to make it seen as one operation but not sure if it's worth of.

**Comment by Emixam23** [comment]
Hello,

The goal here is to remove the data related to an user and do not pay/use quotas for users that left our app :) 

If we can't remove a feed, then this one will keep on getting updated, so quota wll be lost for nothing and so, money by the end. "Unfollow many is only for enterprise" -> Ok, but even with this, it costs us a lot of apicall/feedupdates to remove all the followings/followers..

What I am looking for is a simple solution where we can just "destroy (if this words fits best)" a given feed when/if required.

Thanks

**Comment by ferhatelmas** [comment]
OK, then it's 2. and it's not supported in the server. This is a feature request in the API.

We want to add it but not enough bandwidth to do in a very short time span.

**Comment by ferhatelmas** [comment]
Closing this since server support is missing, not related to SDK.
