### ISSUE TITLE
http2: server sent GOAWAY and closed the connection; ErrCode=ENHANCE_YOUR_CALM

### ISSUE THREAD

**Issue by Emixam23** [GetStream/stream-go2#97]
Hey,

Yesterday we basically tested the work we've done around getstream but today, testing this time some load tests, we had the following issue:

```
"error": " an error append while getting the activities: cannot perform request: 
Get https://api.stream-io-api.com/api/v1.0/activities/?api_key=XXXXXXXXXXXX&ids=20bef400-cbf6-11ea-8080-80006b14301b%2C20bef400-cbf6-11ea-8080-80006b14301b%2C20bef400-cbf6-11ea-8080-80006b14301b%2C21578a80-cbf6-11ea-8080-800061970e19%2C21578a80- **<text made smaller>** -cbf6-11ea-8080-800167e7f094%2C4b10b180-cbf6-11ea-8080-800063d998ff%2C4b10b180-cbf6-11ea-8080-800063d998ff: 
http2: server sent GOAWAY and closed the connection; LastStreamID=1, ErrCode=ENHANCE_YOUR_CALM, debug=\"\""
```

As of today, we have a project in Development with only flat_feeds

Thanks for any direction

**Comment by ferhatelmas** [comment]
Could you also share the snippet where this is called ? I suspect `response.Body.Close` isn't forgotten to be closed somewhere.

**Comment by Emixam23** [comment]
```
func (getStream *GetStream) GetActivitiesByIDs(activitiesIDs []string) ([]*stream.Activity, error) {

	var activities = make([]*stream.Activity, 0)

	res, err := getStream.client.GetActivitiesByID(activitiesIDs...)
	if err != nil {
		return activities, errors.New(fmt.Sprintf("an error append while getting the activities: %v\n", err))
	}

	for _, elem := range res.Results {
		activities = append(activities, &elem)
	}

	return activities, nil
}
```

**Comment by ferhatelmas** [comment]
Ok, there are two things in place here:

* The number of activities that can be retrieved with a single request is limited to 100 ([docs](https://getstream.io/docs/add_many_activities/?language=go#batch-get-activities-by-id)).
* There was a bug regarding body close (https://github.com/GetStream/stream-go2/commit/8adacfb91e945fe5b86633d07dd5c92b5124d13a) in that version which was fixed and it seems you're exactly hitting it via 400 due to above, could you upgrade to the latest if possible.

I will close the ticket but if you see it's still there after updating with above points, please reopen.

**Comment by Emixam23** [comment]
I just `go get -u` this morning so... And regarding directly into your SDK code, I have the `close` for the body in the client.request 

I will now batch then and rework it but I am gonna read the link you gave. I just would like extra information (not related to the question but to a "similar bug"): Can you tell me what's the differences between Production app and Development app? Because last time we had a too many request situation where the request got explicitly discarded. 

Thanks!

**Comment by ferhatelmas** [comment]
The suffix added to import path is import 

```sh
go get -u github.com/GetStream/stream-go2/v4
```

This is for v4 and you won't pick any changes for `v5`. Thus, you need to pull via

```sh
go get -u github.com/GetStream/stream-go2/v5
```

For your second question, there are two differences:
* some checks are applied for prod apps so that you can't mess the data or config by mistake
* rate limits might be different

**Comment by Emixam23** [comment]
Alright, we're now testing using v5.

I was asking regarding the difference between Production and Development because we, today, got the following (as last time):

![image](https://user-images.githubusercontent.com/6987848/88191338-a022e680-cc3b-11ea-925a-e725970f811a.png)

**Comment by Emixam23** [comment]
Hi,

alright we're on v5 and it seems to work but there is a small limitation which I didn't find in the documentation:

`remove activities has a limit of 300/minute`

Thanks for your help

**Comment by Emixam23** [comment]
Hey,

I was just checking your SDK code and found out that in request(), `req.Close = true` might be missing:
https://stackoverflow.com/a/19006050/6093604

maybe something to check, i am not sure

**Comment by ferhatelmas** [comment]
It might have effect for conn reuse so performance but good call, thanks, will check it.
